### ISSUE TITLE
Feature Request - Discord Bot pterodactyl egg

### ISSUE THREAD

**Issue by Miliviu** [iComputerfreak/FoundryWorldSwitcher#2]
I think it'd be quite useful to have a pterodactyl egg for the bot if we have to run FoundryVTT in pterodactyl!

**Comment by iComputerfreak** [comment]
Makes sense. I will see when I have the time to do that.

**Comment by iComputerfreak** [comment]
Was a bit more difficult than I thought, since I couldn't just use the existing docker container, but I think I got it now.

As soon as [the pipeline](https://github.com/iComputerfreak/FoundryWorldSwitcher/actions/runs/11427611916) succeeds, you should be able to install the bot via the egg in `pterodactyl_eggs/foundry_world_switcher`. Let me know if you have any issues.

Also, be prepared to wait a long time for the server installation. Building the executable took about 10 minutes on my server.
